server:
  port: 80
spring:
  datasource:
    username: postgres
    password: 123
    url: jdbc:postgresql://localhost:5432/fast_food_db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
    type: redis
    redis:
      time-to-live: 16h
  data:
    redis:
      host: localhost
      port: 6379
  sql:
    init:
      mode: always

app:
  jwt:
    expireDate: 7
    secretKey: '03d2430e18744da8db2b8dbd64a64977be5c1a7f06d52197c9b8113a3b552c69'
  base-path: 'C:\Users\User\Desktop\projects\app-fast-food\files'