package uz.pdp.appfastfood.enums;

public enum PermissionEnum {
    CATEGORY_CREATE,
    CATEGORY_UPDATE,
    CATEGORY_DELETE,

    ATTACHMENT_CREATE,
    ATTACHMENT_UPDATE,
    ATTACHMENT_DELETE,

    PRODUCT_CREATE,
    PRODUCT_UPDATE,
    PRODUCT_DELETE,

    REGION_CREATE,
    REGION_UPDATE,
    REGION_DELETE,

    FILIAL_CREATE,
    FILIAL_UPDATE,
    FILIAL_DELETE,

    ORDER_UPDATE,
    ORDER_READ,
    ORDER_READ_ALL,

    FROM_SUPPORT_SEND_MESSAGE,
    SUPPORT_READ_ALL,

    EMPLOYEE_READ,
    EMPLOYEE_CREATE,
    EMPLOYEE_UPDATE,
    EMPLOYEE_DELETE,

    THOUGHT_READ,
    THOUGHT_DELETE,

    DELIVERY_CREATE,
    DELIVERY_UPDATE,
    DELIVERY_DELETE,

    USER_READ,
    USER_CHANGE_STATUS,
    USER_DELETE,

    PAYMENT_READ,

    PAYMENT_DELETE,

}
